strategy: "motif"
debug: false
epochs: 100
lr: 0.001
weight_decay: 1e-06
batch_size: 100
warmup: 10
num_workers: 4

rewire_iters: 100
rec_loss: "full" 
lam_mot: 1.0
lam_sup: 1.0    
lam_sigma: 1.0
rec_epochs: 20
rec_samples: 20
epsilon: 0.2
theta: 0.1
volume: false
beta: 1.0
simfunc: 'wwl'
