defaults:
  - _self_
  - task: alphafold
  - representation: graph 
  - model: graph 
  - training: motif 
  - paths: default
  - optional best_model: ${task}_${representation}
  - pretrain: default
  - debug: null

seed: 0

# output directory, generated dynamically on each run
hydra:
  run:
    dir: outputs/${hydra.job.override_dirname}/seed=${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
